/**
 * AS-TC-001 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-001 [negative/api] startDate after endDate is rejected
 * Requirement: REQ-003, REQ-011
 * Rule:        BR-001 Start date must be earlier than end date.
 * Dataset:     DS-TC-001 (SYNTHETIC, seed TC-001:1.0.0)
 * Expected:    rejected with INVALID_DATE_RANGE
 */
import { test, expect } from '../support/aqe';

test('TC-001 startDate after endDate is rejected', { tag: ["@BR-001","@REQ-003","@REQ-011","@negative","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-001');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-001: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-001: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-001: error codes').toContain('INVALID_DATE_RANGE');
});
