/**
 * AS-TC-002 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-002 [boundary/api] startDate equal to endDate is rejected
 * Requirement: REQ-003, REQ-011
 * Rule:        BR-001 Start date must be earlier than end date.
 * Dataset:     DS-TC-002 (SYNTHETIC, seed TC-002:1.0.0)
 * Expected:    rejected with INVALID_DATE_RANGE
 */
import { test, expect } from '../support/aqe';

test('TC-002 startDate equal to endDate is rejected', { tag: ["@BR-001","@REQ-003","@REQ-011","@boundary","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-002');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-001: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-001: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-001: error codes').toContain('INVALID_DATE_RANGE');
});
