/**
 * AS-TC-022 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-022 [negative/api] Declined synthetic payment token is rejected
 * Requirement: REQ-020
 * Rule:        BR-D02 Payment must be authorized by the payment gateway.
 * Dataset:     DS-TC-022 (SYNTHETIC, seed TC-022:1.0.0)
 * Expected:    rejected with PAYMENT_NOT_AUTHORIZED
 */
import { test, expect } from '../support/aqe';

test('TC-022 Declined synthetic payment token is rejected', { tag: ["@BR-D02","@REQ-020","@negative","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-022');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-D02: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-D02: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-D02: error codes').toContain('PAYMENT_NOT_AUTHORIZED');
});
