/**
 * AS-TC-013 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-013 [positive/api] Approved payment.paymentMethod INVOICE is accepted
 * Requirement: REQ-006, REQ-014
 * Rule:        BR-004 An approved payment method is required.
 * Dataset:     DS-TC-013 (SYNTHETIC, seed TC-013:1.0.0)
 * Expected:    success, status CONFIRMED
 */
import { test, expect, GET_RESERVATION, Reservation } from '../support/aqe';

test('TC-013 Approved payment.paymentMethod INVOICE is accepted', { tag: ["@BR-004","@REQ-006","@REQ-014","@positive","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-013');
  const result = await aqe.createReservation(ds.values);
  expect(result.errors, 'BR-004: validation errors').toEqual([]);
  expect(result.success, 'BR-004: createReservation.success').toBe(true);
  expect(result.reservation?.confirmationNumber, 'BR-005: confirmation number format').toMatch(/^CNF-[A-Z0-9]{8}$/);
  expect(result.reservation?.status, 'reservation status').toBe('CONFIRMED');
  expect(result.reservation?.payment.paymentToken, 'payment token returned masked').toMatch(/^tok_\*{4}/);
  const read = await aqe.gql<{ reservation: Reservation | null }>(GET_RESERVATION, { confirmationNumber: result.reservation!.confirmationNumber }, 'reservation');
  expect(read.reservation?.reservationId, 'reservation is retrievable by confirmation number').toBe(result.reservation!.reservationId);
});
