/**
 * AS-TC-012 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-012 [negative/api] Unapproved payment.paymentMethod CASH is rejected
 * Requirement: REQ-006, REQ-014
 * Rule:        BR-004 An approved payment method is required.
 * Dataset:     DS-TC-012 (SYNTHETIC, seed TC-012:1.0.0)
 * Expected:    rejected with PAYMENT_METHOD_NOT_APPROVED
 */
import { test, expect } from '../support/aqe';

test('TC-012 Unapproved payment.paymentMethod CASH is rejected', { tag: ["@BR-004","@REQ-006","@REQ-014","@negative","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-012');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-004: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-004: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-004: error codes').toContain('PAYMENT_METHOD_NOT_APPROVED');
});
