/**
 * AS-TC-010 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-010 [negative/api] Unknown locationId is rejected
 * Requirement: REQ-005, REQ-013
 * Rule:        BR-003 A valid location is required.
 * Dataset:     DS-TC-010 (SYNTHETIC, seed TC-010:1.0.0)
 * Expected:    rejected with INVALID_LOCATION
 */
import { test, expect } from '../support/aqe';

test('TC-010 Unknown locationId is rejected', { tag: ["@BR-003","@REQ-005","@REQ-013","@negative","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-010');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-003: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-003: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-003: error codes').toContain('INVALID_LOCATION');
});
