/**
 * AS-TC-017 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-017 [negative/api] Missing customer.email is rejected
 * Requirement: REQ-007, REQ-016
 * Rule:        BR-006 Required customer fields must be supplied.
 * Dataset:     DS-TC-017 (SYNTHETIC, seed TC-017:1.0.0)
 * Expected:    rejected with MISSING_REQUIRED_FIELD
 */
import { test, expect } from '../support/aqe';

test('TC-017 Missing customer.email is rejected', { tag: ["@BR-006","@REQ-007","@REQ-016","@negative","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-017');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-006: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-006: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-006: error codes').toContain('MISSING_REQUIRED_FIELD');
});
