/**
 * AS-TC-014 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-014 [smoke/api] Smoke: createReservation with valid synthetic data returns a confirmation number
 * Requirement: REQ-001, REQ-002, REQ-015
 * Rule:        BR-005 A confirmation number must be generated after successful creation.
 * Dataset:     DS-TC-014 (SYNTHETIC, seed TC-014:1.0.0)
 * Expected:    success, status CONFIRMED
 */
import { test, expect, GET_RESERVATION, Reservation } from '../support/aqe';

test('TC-014 Smoke: createReservation with valid synthetic data returns a confirmation number', { tag: ["@BR-005","@REQ-001","@REQ-002","@REQ-015","@smoke","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-014');
  const result = await aqe.createReservation(ds.values);
  expect(result.errors, 'BR-005: validation errors').toEqual([]);
  expect(result.success, 'BR-005: createReservation.success').toBe(true);
  expect(result.reservation?.confirmationNumber, 'BR-005: confirmation number format').toMatch(/^CNF-[A-Z0-9]{8}$/);
  expect(result.reservation?.status, 'reservation status').toBe('CONFIRMED');
  expect(result.reservation?.payment.paymentToken, 'payment token returned masked').toMatch(/^tok_\*{4}/);
  const read = await aqe.gql<{ reservation: Reservation | null }>(GET_RESERVATION, { confirmationNumber: result.reservation!.confirmationNumber }, 'reservation');
  expect(read.reservation?.reservationId, 'reservation is retrievable by confirmation number').toBe(result.reservation!.reservationId);
});
