/**
 * AS-TC-015 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-015 [positive/ui] Service associate creates a reservation in the console and receives a confirmation number
 * Requirement: REQ-001, REQ-002, REQ-015
 * Rule:        BR-005 A confirmation number must be generated after successful creation.
 * Dataset:     DS-TC-015 (SYNTHETIC, seed TC-015:1.0.0)
 * Expected:    success, status CONFIRMED
 */
import { test, expect } from '../support/aqe';
import { ReservationConsole } from '../support/reservation-console';

test('TC-015 Service associate creates a reservation in the console and receives a confirmation number', { tag: ["@BR-005","@REQ-001","@REQ-002","@REQ-015","@positive","@ui"] }, async ({ page, aqe }) => {
  const ds = aqe.dataset('DS-TC-015');
  const ui = new ReservationConsole(page);
  await ui.open();
  await ui.fillCreate(ds.values);
  await ui.submitCreate();
  await aqe.screenshot(page, 'create-outcome');
  await expect(ui.outcome(), 'BR-005: create outcome').toHaveAttribute('data-testid', 'success-toast');
  const confirmation = (await page.getByTestId('confirmation-number').textContent()) ?? '';
  expect(confirmation, 'BR-005: confirmation number format').toMatch(/^CNF-[A-Z0-9]{8}$/);
  await expect(page.getByTestId('reservation-status')).toHaveText('CONFIRMED');
});
