/**
 * AS-TC-020 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-020 [negative/api] Unavailable SUITE at LOC-SYN-002 for booked dates is rejected
 * Requirement: REQ-017, REQ-018
 * Rule:        BR-007 The requested resource must be available for the selected dates.
 * Dataset:     DS-TC-020 (SYNTHETIC, seed TC-020:1.0.0)
 * Expected:    rejected with RESOURCE_UNAVAILABLE
 */
import { test, expect } from '../support/aqe';

test('TC-020 Unavailable SUITE at LOC-SYN-002 for booked dates is rejected', { tag: ["@BR-007","@REQ-017","@REQ-018","@negative","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-020');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-007: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-007: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-007: error codes').toContain('RESOURCE_UNAVAILABLE');
});
