/**
 * AS-TC-007 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-007 [boundary/api] customerCount = 1 is accepted
 * Requirement: REQ-004, REQ-009, REQ-012
 * Rule:        BR-002 Customer count must be greater than zero.
 * Dataset:     DS-TC-007 (SYNTHETIC, seed TC-007:1.0.0)
 * Expected:    success, status CONFIRMED
 */
import { test, expect, GET_RESERVATION, Reservation } from '../support/aqe';

test('TC-007 customerCount = 1 is accepted', { tag: ["@BR-002","@REQ-004","@REQ-009","@REQ-012","@boundary","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-007');
  const result = await aqe.createReservation(ds.values);
  expect(result.errors, 'BR-002: validation errors').toEqual([]);
  expect(result.success, 'BR-002: createReservation.success').toBe(true);
  expect(result.reservation?.confirmationNumber, 'BR-005: confirmation number format').toMatch(/^CNF-[A-Z0-9]{8}$/);
  expect(result.reservation?.status, 'reservation status').toBe('CONFIRMED');
  expect(result.reservation?.payment.paymentToken, 'payment token returned masked').toMatch(/^tok_\*{4}/);
  const read = await aqe.gql<{ reservation: Reservation | null }>(GET_RESERVATION, { confirmationNumber: result.reservation!.confirmationNumber }, 'reservation');
  expect(read.reservation?.reservationId, 'reservation is retrievable by confirmation number').toBe(result.reservation!.reservationId);
});
