/**
 * AS-TC-006 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-006 [negative/api] customerCount = -1 is rejected
 * Requirement: REQ-004, REQ-009, REQ-012
 * Rule:        BR-002 Customer count must be greater than zero.
 * Dataset:     DS-TC-006 (SYNTHETIC, seed TC-006:1.0.0)
 * Expected:    rejected with INVALID_CUSTOMER_COUNT
 */
import { test, expect } from '../support/aqe';

test('TC-006 customerCount = -1 is rejected', { tag: ["@BR-002","@REQ-004","@REQ-009","@REQ-012","@negative","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-006');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-002: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-002: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-002: error codes').toContain('INVALID_CUSTOMER_COUNT');
});
