/**
 * AS-TC-009 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-009 [boundary/api] customerCount = 11 is rejected
 * Requirement: REQ-004, REQ-009, REQ-012
 * Rule:        BR-002 Customer count must be greater than zero.
 * Dataset:     DS-TC-009 (SYNTHETIC, seed TC-009:1.0.0)
 * Expected:    rejected with INVALID_CUSTOMER_COUNT
 */
import { test, expect } from '../support/aqe';

test('TC-009 customerCount = 11 is rejected', { tag: ["@BR-002","@REQ-004","@REQ-009","@REQ-012","@boundary","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-009');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-002: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-002: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-002: error codes').toContain('INVALID_CUSTOMER_COUNT');
});
