/**
 * AS-TC-005 — generated by the Automation Agent (cycle CYC-0001)
 * Test case:   TC-005 [boundary/ui] customerCount = 0 is rejected in the console
 * Requirement: REQ-004, REQ-009, REQ-012
 * Rule:        BR-002 Customer count must be greater than zero.
 * Dataset:     DS-TC-005 (SYNTHETIC, seed TC-005:1.0.0)
 * Expected:    rejected with INVALID_CUSTOMER_COUNT
 */
import { test, expect } from '../support/aqe';
import { ReservationConsole } from '../support/reservation-console';

test('TC-005 customerCount = 0 is rejected in the console', { tag: ["@BR-002","@REQ-004","@REQ-009","@REQ-012","@boundary","@ui"] }, async ({ page, aqe }) => {
  const ds = aqe.dataset('DS-TC-005');
  const ui = new ReservationConsole(page);
  await ui.open();
  await ui.fillCreate(ds.values);
  await ui.submitCreate();
  await aqe.screenshot(page, 'create-outcome');
  await expect(ui.outcome(), 'BR-002: create outcome').toHaveAttribute('data-testid', 'error-toast');
  await expect(ui.error('INVALID_CUSTOMER_COUNT'), 'BR-002: INVALID_CUSTOMER_COUNT shown').toBeVisible();
  await expect(page.getByTestId('confirmation-number'), 'BR-002: no confirmation number issued').toHaveCount(0);
});
