/**
 * Automation Agent: generates a runnable Playwright + TypeScript suite (UI specs through the
 * Lightning-style console, GraphQL API specs through the contract), reusable fixtures,
 * assertions and utilities. Every script header links requirement, rule, test case and dataset.
 */
import fs from 'node:fs';
import path from 'node:path';
import { sha256 } from '../../shared/hash';
import { rel } from '../../shared/paths';
import { AutomationScript, BusinessRule, Dataset, TestCase } from '../types';

export const AGENT = 'Automation Agent';

const RESERVATION_FIELDS = 'reservationId confirmationNumber locationId startDate endDate customerCount resourceType status createdAt payment { paymentMethod paymentToken authorizationStatus }';

export const SUPPORT_AQE = `/* Generated by the Automation Agent: shared fixtures, GraphQL client, masking and evidence helpers. */
import fs from 'node:fs';
import path from 'node:path';
import { test as base, expect, Page, TestInfo } from '@playwright/test';

export interface DatasetValues {
  locationId: string | null;
  startDate: string | null;
  endDate: string | null;
  customerCount: number | null;
  resourceType: string | null;
  customer: { firstName: string | null; lastName: string | null; email: string | null };
  payment: { paymentMethod: string | null; paymentToken: string | null };
}
export interface Dataset { id: string; classification: 'SYNTHETIC'; values: DatasetValues; provenance: { generator: string; seed: string } }
export interface GqlError { code: string; field: string | null; message: string; ruleId: string | null }
export interface Reservation { reservationId: string; confirmationNumber: string; status: string; customerCount: number; payment: { paymentToken: string } }
export interface Payload { success: boolean; reservation: Reservation | null; errors: GqlError[] }

export const CREATE_RESERVATION = \`mutation CreateReservation($input: CreateReservationInput!) { createReservation(input: $input) { success errors { code field message ruleId } reservation { ${RESERVATION_FIELDS} } } }\`;
export const GET_RESERVATION = \`query Reservation($confirmationNumber: String!) { reservation(confirmationNumber: $confirmationNumber) { ${RESERVATION_FIELDS} } }\`;

const DATA_DIR = path.join(__dirname, '..', 'data');
const SENSITIVE = ['email', 'paymentToken', 'firstName', 'lastName'];

export function mask(value: unknown, key = ''): unknown {
  if (Array.isArray(value)) return value.map((v) => mask(v, key));
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, mask(v, k)]));
  if (typeof value !== 'string' || !SENSITIVE.includes(key)) return value;
  if (key === 'paymentToken') return \`tok_****\${value.slice(-4)}\`;
  if (key === 'email') return value.replace(/^(.).*@/, '$1***@');
  return value ? \`\${value[0]}***\` : value;
}

export const testId = (info: TestInfo) => /^(\\S+)/.exec(info.title)?.[1] ?? 'unknown';

export interface Aqe {
  dataset(id: string): Dataset;
  gql<T>(query: string, variables: Record<string, unknown>, label: string): Promise<T>;
  createReservation(values: DatasetValues): Promise<Payload>;
  screenshot(page: Page, name: string): Promise<void>;
}

export const test = base.extend<{ aqe: Aqe }>({
  page: async ({ page }, use, testInfo) => {
    await page.setExtraHTTPHeaders({ 'x-aqe-test-id': testId(testInfo) });
    await use(page);
  },
  aqe: async ({ request }, use, testInfo) => {
    const aqe: Aqe = {
      dataset(id) {
        const ds = JSON.parse(fs.readFileSync(path.join(DATA_DIR, \`\${id}.json\`), 'utf8')) as Dataset;
        if (ds.classification !== 'SYNTHETIC') throw new Error(\`\${id} is not SYNTHETIC\`);
        return ds;
      },
      async gql<T>(query: string, variables: Record<string, unknown>, label: string) {
        const started = Date.now();
        const res = await request.post('/graphql', { data: { query, variables }, headers: { 'x-aqe-test-id': testId(testInfo) } });
        const body = (await res.json()) as { data?: T; errors?: { message: string }[] };
        await testInfo.attach(\`request-response-\${label}\`, {
          body: JSON.stringify({ request: { operation: label, variables: mask(variables) }, response: { status: res.status(), body: mask(body) }, durationMs: Date.now() - started }, null, 2),
          contentType: 'application/json',
        });
        expect(body.errors, \`GraphQL errors for \${label}\`).toBeUndefined();
        return body.data as T;
      },
      async createReservation(values) {
        const data = await aqe.gql<{ createReservation: Payload }>(CREATE_RESERVATION, { input: values }, 'createReservation');
        return data.createReservation;
      },
      async screenshot(page, name) {
        const body = await page.screenshot({ fullPage: true, mask: [page.locator('[data-sensitive]')] });
        await testInfo.attach(\`screenshot-\${name}\`, { body, contentType: 'image/png' });
      },
    };
    await use(aqe);
  },
});

export { expect };
`;

export const SUPPORT_CONSOLE = `/* Generated by the Automation Agent: page object for the Lightning-style reservation console. */
import { expect, Locator, Page } from '@playwright/test';
import { DatasetValues } from './aqe';

export class ReservationConsole {
  constructor(readonly page: Page) {}

  async open() {
    await this.page.goto('/');
    await expect(this.page.locator('body[data-ready="true"]')).toBeAttached();
  }

  private async fill(testId: string, value: string | number | null) {
    if (value === null || value === undefined) return;
    await this.page.getByTestId(testId).fill(String(value));
  }

  private async select(testId: string, value: string | null) {
    if (value) await this.page.getByTestId(testId).selectOption(value);
  }

  async fillCreate(v: DatasetValues) {
    await this.select('locationId', v.locationId);
    await this.select('resourceType', v.resourceType);
    await this.fill('startDate', v.startDate);
    await this.fill('endDate', v.endDate);
    await this.fill('customerCount', v.customerCount);
    await this.fill('firstName', v.customer.firstName);
    await this.fill('lastName', v.customer.lastName);
    await this.fill('email', v.customer.email);
    await this.select('paymentMethod', v.payment.paymentMethod);
    await this.fill('paymentToken', v.payment.paymentToken);
  }

  async submitCreate() {
    await this.page.getByTestId('submit-create').click();
    await this.outcome().waitFor();
  }

  outcome(): Locator {
    return this.page.getByTestId('create-result').locator('.toast');
  }

  error(code: string): Locator {
    return this.page.locator(\`[data-testid="error"][data-code="\${code}"]\`);
  }

  async search(confirmationNumber: string) {
    await this.page.getByTestId('tab-search').click();
    await this.page.getByTestId('search-confirmation').fill(confirmationNumber);
    await this.page.getByTestId('submit-search').click();
    return this.page.getByTestId('search-row');
  }

  async cancel(confirmationNumber: string, reason: string) {
    await this.page.getByTestId('tab-manage').click();
    await this.page.getByTestId('manage-confirmation').fill(confirmationNumber);
    await this.page.getByTestId('cancel-reason').fill(reason);
    await this.page.getByTestId('submit-cancel').click();
    return this.page.getByTestId('manage-result').locator('.toast');
  }
}
`;

export const PLAYWRIGHT_CONFIG = `/* Generated by the Automation Agent. Executed by the Execution Agent with AQE_BASE_URL and AQE_RUN_DIR set. */
import { defineConfig, devices } from '@playwright/test';

const baseURL = process.env.AQE_BASE_URL;
if (!baseURL) throw new Error('AQE_BASE_URL is required (the Execution Agent sets it to the local demo service)');
const runDir = process.env.AQE_RUN_DIR || './.run';

export default defineConfig({
  testDir: './tests',
  outputDir: \`\${runDir}/test-output\`,
  fullyParallel: true,
  workers: Number(process.env.AQE_WORKERS || 4),
  retries: 0,
  timeout: 30_000,
  expect: { timeout: 4_000 },
  reporter: [['json', { outputFile: \`\${runDir}/playwright-report.json\` }], ['list']],
  use: { ...devices['Desktop Chrome'], baseURL, trace: 'on', screenshot: 'off', video: 'off' },
});
`;

function header(tc: TestCase, ds: Dataset, rules: BusinessRule[], scriptId: string, origin: string) {
  const r = rules.filter((b) => tc.ruleIds.includes(b.id));
  return `/**
 * ${scriptId} — generated by the ${AGENT} (${origin})
 * Test case:   ${tc.id} [${tc.type}/${tc.channel}] ${tc.title}
 * Requirement: ${tc.requirementIds.join(', ')}
 * Rule:        ${r.map((b) => `${b.id} ${b.text}`).join(' | ')}
 * Dataset:     ${ds.id} (SYNTHETIC, seed ${ds.provenance.seed})
 * Expected:    ${tc.expected.success ? `success, status ${tc.expected.status}` : `rejected with ${tc.expected.errorCode}`}
 */`;
}

export function specSource(tc: TestCase, ds: Dataset, rules: BusinessRule[], scriptId: string, origin: string): string {
  const rule = tc.ruleIds[0];
  const tags = JSON.stringify([...tc.ruleIds, ...tc.requirementIds, tc.type, tc.channel].map((t) => `@${t}`));
  const title = `${tc.id} ${tc.title}`.replace(/'/g, "\\'");
  const pattern = tc.expected.confirmationPattern ?? '^CNF-[A-Z0-9]{8}$';
  const lines: string[] = [header(tc, ds, rules, scriptId, origin)];
  if (tc.channel === 'api') {
    lines.push(`import { test, expect${tc.expected.success ? ', GET_RESERVATION, Reservation' : ''} } from '../support/aqe';

test('${title}', { tag: ${tags} }, async ({ aqe }) => {
  const ds = aqe.dataset('${ds.id}');
  const result = await aqe.createReservation(ds.values);`);
    if (tc.expected.success) {
      lines.push(`  expect(result.errors, '${rule}: validation errors').toEqual([]);
  expect(result.success, '${rule}: createReservation.success').toBe(true);
  expect(result.reservation?.confirmationNumber, 'BR-005: confirmation number format').toMatch(/${pattern}/);
  expect(result.reservation?.status, 'reservation status').toBe('${tc.expected.status}');
  expect(result.reservation?.payment.paymentToken, 'payment token returned masked').toMatch(/^tok_\\*{4}/);
  const read = await aqe.gql<{ reservation: Reservation | null }>(GET_RESERVATION, { confirmationNumber: result.reservation!.confirmationNumber }, 'reservation');
  expect(read.reservation?.reservationId, 'reservation is retrievable by confirmation number').toBe(result.reservation!.reservationId);
});`);
    } else {
      lines.push(`  expect(result.success, '${rule}: createReservation.success').toBe(false);
  expect(result.reservation, '${rule}: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), '${rule}: error codes').toContain('${tc.expected.errorCode}');
});`);
    }
  } else {
    lines.push(`import { test, expect } from '../support/aqe';
import { ReservationConsole } from '../support/reservation-console';

test('${title}', { tag: ${tags} }, async ({ page, aqe }) => {
  const ds = aqe.dataset('${ds.id}');
  const ui = new ReservationConsole(page);
  await ui.open();
  await ui.fillCreate(ds.values);
  await ui.submitCreate();
  await aqe.screenshot(page, 'create-outcome');`);
    if (!tc.expected.success) {
      lines.push(`  await expect(ui.outcome(), '${rule}: create outcome').toHaveAttribute('data-testid', 'error-toast');
  await expect(ui.error('${tc.expected.errorCode}'), '${rule}: ${tc.expected.errorCode} shown').toBeVisible();
  await expect(page.getByTestId('confirmation-number'), '${rule}: no confirmation number issued').toHaveCount(0);
});`);
    } else {
      lines.push(`  await expect(ui.outcome(), '${rule}: create outcome').toHaveAttribute('data-testid', 'success-toast');
  const confirmation = (await page.getByTestId('confirmation-number').textContent()) ?? '';
  expect(confirmation, 'BR-005: confirmation number format').toMatch(/${pattern}/);
  await expect(page.getByTestId('reservation-status')).toHaveText('CONFIRMED');`);
      if (tc.flow === 'create-search-cancel') {
        lines.push(`  const rows = await ui.search(confirmation);
  await expect(rows, 'search finds the reservation').toHaveCount(1);
  await expect(rows.first().getByTestId('row-status')).toHaveText('CONFIRMED');
  await aqe.screenshot(page, 'search-result');
  const toast = await ui.cancel(confirmation, 'Synthetic cancellation for automated test');
  await expect(toast, 'cancel outcome').toHaveAttribute('data-testid', 'success-toast');
  const after = await ui.search(confirmation);
  await expect(after.first().getByTestId('row-status'), 'status after cancel').toHaveText('${tc.expected.status}');
  await aqe.screenshot(page, 'after-cancel');`);
      }
      lines.push('});');
    }
  }
  return `${lines.join('\n')}\n`;
}

/** Writes the suite into <dir> and returns script records linked to test cases and datasets. */
export function generateSuite(dir: string, home: string, testCases: TestCase[], datasets: Dataset[], rules: BusinessRule[], origin: string, idPrefix = 'AS-'): AutomationScript[] {
  fs.mkdirSync(path.join(dir, 'tests'), { recursive: true });
  fs.mkdirSync(path.join(dir, 'support'), { recursive: true });
  fs.mkdirSync(path.join(dir, 'data'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'playwright.config.ts'), PLAYWRIGHT_CONFIG);
  fs.writeFileSync(path.join(dir, 'support', 'aqe.ts'), SUPPORT_AQE);
  fs.writeFileSync(path.join(dir, 'support', 'reservation-console.ts'), SUPPORT_CONSOLE);
  return testCases.map((tc) => {
    const ds = datasets.find((d) => d.testCaseId === tc.id)!;
    const id = `${idPrefix}${tc.id}`;
    fs.writeFileSync(path.join(dir, 'data', `${ds.id}.json`), `${JSON.stringify({ id: ds.id, classification: ds.classification, provenance: ds.provenance, values: ds.values }, null, 2)}\n`);
    const source = specSource(tc, ds, rules, id, origin);
    const file = path.join(dir, 'tests', `${tc.id}.${tc.channel}.spec.ts`);
    fs.writeFileSync(file, source);
    return { id, testCaseId: tc.id, datasetId: ds.id, ruleIds: tc.ruleIds, requirementIds: tc.requirementIds, channel: tc.channel, file: rel(home, file), sha256: sha256(source) };
  });
}
