/**
 * AS-TC-016 — generated by the Automation Agent (cycle CYC-0002)
 * Test case:   TC-016 [e2e/ui] End to end: create, search by confirmation number and cancel the reservation
 * Requirement: REQ-001, REQ-002, REQ-015
 * Rule:        BR-005 A confirmation number must be generated after successful creation.
 * Dataset:     DS-TC-016 (SYNTHETIC, seed TC-016:1.0.0)
 * Expected:    success, status CANCELLED
 */
import { test, expect } from '../support/aqe';
import { ReservationConsole } from '../support/reservation-console';

test('TC-016 End to end: create, search by confirmation number and cancel the reservation', { tag: ["@BR-005","@REQ-001","@REQ-002","@REQ-015","@e2e","@ui"] }, async ({ page, aqe }) => {
  const ds = aqe.dataset('DS-TC-016');
  const ui = new ReservationConsole(page);
  await ui.open();
  await ui.fillCreate(ds.values);
  await ui.submitCreate();
  await aqe.screenshot(page, 'create-outcome');
  await expect(ui.outcome(), 'BR-005: create outcome').toHaveAttribute('data-testid', 'success-toast');
  const confirmation = (await page.getByTestId('confirmation-number').textContent()) ?? '';
  expect(confirmation, 'BR-005: confirmation number format').toMatch(/^CNF-[A-Z0-9]{8}$/);
  await expect(page.getByTestId('reservation-status')).toHaveText('CONFIRMED');
  const rows = await ui.search(confirmation);
  await expect(rows, 'search finds the reservation').toHaveCount(1);
  await expect(rows.first().getByTestId('row-status')).toHaveText('CONFIRMED');
  await aqe.screenshot(page, 'search-result');
  const toast = await ui.cancel(confirmation, 'Synthetic cancellation for automated test');
  await expect(toast, 'cancel outcome').toHaveAttribute('data-testid', 'success-toast');
  const after = await ui.search(confirmation);
  await expect(after.first().getByTestId('row-status'), 'status after cancel').toHaveText('CANCELLED');
  await aqe.screenshot(page, 'after-cancel');
});
