/**
 * AS-TC-021 — generated by the Automation Agent (cycle CYC-0002)
 * Test case:   TC-021 [negative/api] Malformed customer.email is rejected
 * Requirement: REQ-019
 * Rule:        BR-D01 Customer email must be valid.
 * Dataset:     DS-TC-021 (SYNTHETIC, seed TC-021:1.0.0)
 * Expected:    rejected with INVALID_EMAIL
 */
import { test, expect } from '../support/aqe';

test('TC-021 Malformed customer.email is rejected', { tag: ["@BR-D01","@REQ-019","@negative","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-021');
  const result = await aqe.createReservation(ds.values);
  expect(result.success, 'BR-D01: createReservation.success').toBe(false);
  expect(result.reservation, 'BR-D01: no reservation created').toBeNull();
  expect(result.errors.map((e) => e.code), 'BR-D01: error codes').toContain('INVALID_EMAIL');
});
