/**
 * AS-TC-003 — generated by the Automation Agent (cycle CYC-0002)
 * Test case:   TC-003 [boundary/api] endDate one day after startDate is accepted
 * Requirement: REQ-003, REQ-011
 * Rule:        BR-001 Start date must be earlier than end date.
 * Dataset:     DS-TC-003 (SYNTHETIC, seed TC-003:1.0.0)
 * Expected:    success, status CONFIRMED
 */
import { test, expect, GET_RESERVATION, Reservation } from '../support/aqe';

test('TC-003 endDate one day after startDate is accepted', { tag: ["@BR-001","@REQ-003","@REQ-011","@boundary","@api"] }, async ({ aqe }) => {
  const ds = aqe.dataset('DS-TC-003');
  const result = await aqe.createReservation(ds.values);
  expect(result.errors, 'BR-001: validation errors').toEqual([]);
  expect(result.success, 'BR-001: createReservation.success').toBe(true);
  expect(result.reservation?.confirmationNumber, 'BR-005: confirmation number format').toMatch(/^CNF-[A-Z0-9]{8}$/);
  expect(result.reservation?.status, 'reservation status').toBe('CONFIRMED');
  expect(result.reservation?.payment.paymentToken, 'payment token returned masked').toMatch(/^tok_\*{4}/);
  const read = await aqe.gql<{ reservation: Reservation | null }>(GET_RESERVATION, { confirmationNumber: result.reservation!.confirmationNumber }, 'reservation');
  expect(read.reservation?.reservationId, 'reservation is retrievable by confirmation number').toBe(result.reservation!.reservationId);
});
