/* Generated by the Automation Agent: page object for the Lightning-style reservation console. */
import { expect, Locator, Page } from '@playwright/test';
import { DatasetValues } from './aqe';

export class ReservationConsole {
  constructor(readonly page: Page) {}

  async open() {
    await this.page.goto('/');
    await expect(this.page.locator('body[data-ready="true"]')).toBeAttached();
  }

  private async fill(testId: string, value: string | number | null) {
    if (value === null || value === undefined) return;
    await this.page.getByTestId(testId).fill(String(value));
  }

  private async select(testId: string, value: string | null) {
    if (value) await this.page.getByTestId(testId).selectOption(value);
  }

  async fillCreate(v: DatasetValues) {
    await this.select('locationId', v.locationId);
    await this.select('resourceType', v.resourceType);
    await this.fill('startDate', v.startDate);
    await this.fill('endDate', v.endDate);
    await this.fill('customerCount', v.customerCount);
    await this.fill('firstName', v.customer.firstName);
    await this.fill('lastName', v.customer.lastName);
    await this.fill('email', v.customer.email);
    await this.select('paymentMethod', v.payment.paymentMethod);
    await this.fill('paymentToken', v.payment.paymentToken);
  }

  async submitCreate() {
    await this.page.getByTestId('submit-create').click();
    await this.outcome().waitFor();
  }

  outcome(): Locator {
    return this.page.getByTestId('create-result').locator('.toast');
  }

  error(code: string): Locator {
    return this.page.locator(`[data-testid="error"][data-code="${code}"]`);
  }

  async search(confirmationNumber: string) {
    await this.page.getByTestId('tab-search').click();
    await this.page.getByTestId('search-confirmation').fill(confirmationNumber);
    await this.page.getByTestId('submit-search').click();
    return this.page.getByTestId('search-row');
  }

  async cancel(confirmationNumber: string, reason: string) {
    await this.page.getByTestId('tab-manage').click();
    await this.page.getByTestId('manage-confirmation').fill(confirmationNumber);
    await this.page.getByTestId('cancel-reason').fill(reason);
    await this.page.getByTestId('submit-cancel').click();
    return this.page.getByTestId('manage-result').locator('.toast');
  }
}
