/**
 * Scripted end-to-end demo: runs a baseline cycle for STORY-001 through all nine agents and
 * the four human gates, recording approvals under the named human running the demo
 * (AQE_DEMO_APPROVER). `--rerun-fixed` adds a second cycle against the fixed service build.
 * `--artifacts-only` regenerates reports and exports for existing cycles without executing.
 */
import fs from 'node:fs';
import path from 'node:path';
import { loadConfig } from '../src/platform/config';
import { Store } from '../src/platform/store';
import { Pipeline } from '../src/platform/pipeline';
import { loadBundle, traceWorkbook } from '../src/platform/bundle';
import { computeMetrics, Metrics, writeReports } from '../src/platform/agents/reporting';
import { resetWorkspace } from '../src/platform/retention';
import { ReviewFinding, SKILLS, TEST_TYPES, Cycle, CycleConfig } from '../src/platform/types';
import { INPUT_FILES } from '../src/platform/inputs';

const approver = process.env.AQE_DEMO_APPROVER || 'Demo QE Lead';
const args = process.argv.slice(2);
const store = new Store();
const config = loadConfig();
const pipeline = new Pipeline(store, config);

function expectStatus(c: Cycle, status: Cycle['status']) {
  if (c.status !== status) {
    const failed = c.stages.find((s) => s.status === 'failed');
    throw new Error(`${c.id} is ${c.status}, expected ${status}${failed ? ` (${failed.id}: ${failed.error})` : ''}`);
  }
}

async function runCycle(overrides: Partial<CycleConfig>, releaseComment: (m: Metrics) => string): Promise<Cycle> {
  const cfg: CycleConfig = { mode: 'baseline', testingTypes: [...TEST_TYPES], channels: ['ui', 'api'], inputs: Object.keys(INPUT_FILES), skills: [...SKILLS], requestedBy: approver, ...overrides };
  let c = pipeline.createCycle(cfg);
  console.log(`\n${c.id} created (${cfg.mode}${cfg.fixedDefects?.length ? `, fixed build: ${cfg.fixedDefects.join(',')}` : ', seeded build'})`);
  c = await pipeline.advance(c.id);
  expectStatus(c, 'waiting-approval');
  const findings = store.readArtifact<ReviewFinding[]>(c.id, 'review/findings.json') ?? [];
  console.log(`  Review Agent: ${findings.length} advisory findings`);
  const findingDecisions = findings.map((f) => ({ findingId: f.id, decision: 'accept' as const, comment: `Accepted: ${f.recommendation}` }));
  pipeline.approve(c.id, 'requirements-baseline', { approver, decision: 'approved', comments: 'Requirements baseline approved after reviewing every finding (npm run demo).', findingDecisions });
  c = await pipeline.advance(c.id);
  const tcs = store.readArtifact<unknown[]>(c.id, 'tests/test-cases.json') ?? [];
  console.log(`  Gate 1 approved -> ${tcs.length} test cases designed`);
  pipeline.approve(c.id, 'test-design', { approver, decision: 'approved', comments: 'Test cases and coverage matrix reviewed.' });
  c = await pipeline.advance(c.id);
  const scripts = store.readArtifact<unknown[]>(c.id, 'automation/scripts.json') ?? [];
  console.log(`  Gate 2 approved -> ${scripts.length} synthetic datasets and Playwright specs generated`);
  pipeline.approve(c.id, 'execution', { approver, decision: 'approved', comments: 'Execution against the local demo service approved.' });
  console.log('  Gate 3 approved -> executing Playwright suite...');
  c = await pipeline.advance(c.id);
  expectStatus(c, 'waiting-approval');
  const m = store.readArtifact<Metrics>(c.id, 'reports/metrics.json')!;
  console.log(`  Execution: ${m.execution.passed}/${m.execution.total} passed, ${m.execution.failed} failed; defects: ${m.defects.total}`);
  console.log(`  Recommendation (rules-based): ${m.recommendation.decision} — ${m.recommendation.reason}`);
  c = pipeline.approve(c.id, 'release', { approver, decision: 'approved', comments: releaseComment(m) });
  console.log(`  Gate 4 signed off -> final baseline ${c.baselineId}`);
  return c;
}

async function regenerate() {
  for (const c of store.listCycles().filter((x) => store.readArtifact(x.id, 'execution/summary.json'))) {
    const b = loadBundle(store, c);
    const excluded = store.readArtifact<unknown[]>(c.id, 'tests/excluded.json')?.length ?? 0;
    writeReports(store, b, computeMetrics(b, store, config, excluded));
    store.artifact(c.id, 'traceability/traceability.xlsx', await traceWorkbook(b));
    console.log(`Regenerated reports and exports for ${c.id}`);
  }
}

function writeIndex() {
  const lines = ['# demo-artifacts', '', 'Generated by `npm run demo` / `npm run artifacts`. All data is SYNTHETIC.', ''];
  for (const c of store.listCycles()) {
    const m = store.readArtifact<Metrics>(c.id, 'reports/metrics.json');
    lines.push(`## ${c.id} (${c.status}${c.demoServiceBuild ? `, ${c.demoServiceBuild}` : ''})`, '');
    if (m) lines.push(`Recommendation: **${m.recommendation.decision}** · ${m.execution.passed}/${m.execution.total} passed · ${m.defects.total} defect(s)`, '');
    const seen = new Set<string>();
    for (const s of c.stages) for (const o of s.outputs) if (!seen.has(o.path)) {
      seen.add(o.path);
      lines.push(`- [${o.label}](${o.path})`);
    }
    lines.push('');
  }
  fs.writeFileSync(path.join(store.home, 'INDEX.md'), `${lines.join('\n')}\n`);
}

async function main() {
  if (args.includes('--artifacts-only') && store.listCycles().some((c) => store.readArtifact(c.id, 'execution/summary.json'))) {
    await regenerate();
  } else {
    resetWorkspace(store, config, approver);
    await runCycle({}, (m) => `Signed off: agree with ${m.recommendation.decision}. ${m.recommendation.conditions[0] ?? ''}`.trim());
    if (args.includes('--rerun-fixed')) await runCycle({ fixedDefects: ['BR-002'] }, (m) => `Signed off: ${m.recommendation.decision} on the fixed build.`);
  }
  writeIndex();
  console.log(`\nArtifacts: ${path.relative(process.cwd(), store.home) || '.'}/INDEX.md`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
