/* Generated by the Automation Agent: shared fixtures, GraphQL client, masking and evidence helpers. */
import fs from 'node:fs';
import path from 'node:path';
import { test as base, expect, Page, TestInfo } from '@playwright/test';

export interface DatasetValues {
  locationId: string | null;
  startDate: string | null;
  endDate: string | null;
  customerCount: number | null;
  resourceType: string | null;
  customer: { firstName: string | null; lastName: string | null; email: string | null };
  payment: { paymentMethod: string | null; paymentToken: string | null };
}
export interface Dataset { id: string; classification: 'SYNTHETIC'; values: DatasetValues; provenance: { generator: string; seed: string } }
export interface GqlError { code: string; field: string | null; message: string; ruleId: string | null }
export interface Reservation { reservationId: string; confirmationNumber: string; status: string; customerCount: number; payment: { paymentToken: string } }
export interface Payload { success: boolean; reservation: Reservation | null; errors: GqlError[] }

export const CREATE_RESERVATION = `mutation CreateReservation($input: CreateReservationInput!) { createReservation(input: $input) { success errors { code field message ruleId } reservation { reservationId confirmationNumber locationId startDate endDate customerCount resourceType status createdAt payment { paymentMethod paymentToken authorizationStatus } } } }`;
export const GET_RESERVATION = `query Reservation($confirmationNumber: String!) { reservation(confirmationNumber: $confirmationNumber) { reservationId confirmationNumber locationId startDate endDate customerCount resourceType status createdAt payment { paymentMethod paymentToken authorizationStatus } } }`;

const DATA_DIR = path.join(__dirname, '..', 'data');
const SENSITIVE = ['email', 'paymentToken', 'firstName', 'lastName'];

export function mask(value: unknown, key = ''): unknown {
  if (Array.isArray(value)) return value.map((v) => mask(v, key));
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, mask(v, k)]));
  if (typeof value !== 'string' || !SENSITIVE.includes(key)) return value;
  if (key === 'paymentToken') return `tok_****${value.slice(-4)}`;
  if (key === 'email') return value.replace(/^(.).*@/, '$1***@');
  return value ? `${value[0]}***` : value;
}

export const testId = (info: TestInfo) => /^(\S+)/.exec(info.title)?.[1] ?? 'unknown';

export interface Aqe {
  dataset(id: string): Dataset;
  gql<T>(query: string, variables: Record<string, unknown>, label: string): Promise<T>;
  createReservation(values: DatasetValues): Promise<Payload>;
  screenshot(page: Page, name: string): Promise<void>;
}

export const test = base.extend<{ aqe: Aqe }>({
  page: async ({ page }, use, testInfo) => {
    await page.setExtraHTTPHeaders({ 'x-aqe-test-id': testId(testInfo) });
    await use(page);
  },
  aqe: async ({ request }, use, testInfo) => {
    const aqe: Aqe = {
      dataset(id) {
        const ds = JSON.parse(fs.readFileSync(path.join(DATA_DIR, `${id}.json`), 'utf8')) as Dataset;
        if (ds.classification !== 'SYNTHETIC') throw new Error(`${id} is not SYNTHETIC`);
        return ds;
      },
      async gql<T>(query: string, variables: Record<string, unknown>, label: string) {
        const started = Date.now();
        const res = await request.post('/graphql', { data: { query, variables }, headers: { 'x-aqe-test-id': testId(testInfo) } });
        const body = (await res.json()) as { data?: T; errors?: { message: string }[] };
        await testInfo.attach(`request-response-${label}`, {
          body: JSON.stringify({ request: { operation: label, variables: mask(variables) }, response: { status: res.status(), body: mask(body) }, durationMs: Date.now() - started }, null, 2),
          contentType: 'application/json',
        });
        expect(body.errors, `GraphQL errors for ${label}`).toBeUndefined();
        return body.data as T;
      },
      async createReservation(values) {
        const data = await aqe.gql<{ createReservation: Payload }>(CREATE_RESERVATION, { input: values }, 'createReservation');
        return data.createReservation;
      },
      async screenshot(page, name) {
        const body = await page.screenshot({ fullPage: true, mask: [page.locator('[data-sensitive]')] });
        await testInfo.attach(`screenshot-${name}`, { body, contentType: 'image/png' });
      },
    };
    await use(aqe);
  },
});

export { expect };
