/* Generated by the Automation Agent. Executed by the Execution Agent with AQE_BASE_URL and AQE_RUN_DIR set. */
import { defineConfig, devices } from '@playwright/test';

const baseURL = process.env.AQE_BASE_URL;
if (!baseURL) throw new Error('AQE_BASE_URL is required (the Execution Agent sets it to the local demo service)');
const runDir = process.env.AQE_RUN_DIR || './.run';

export default defineConfig({
  testDir: './tests',
  outputDir: `${runDir}/test-output`,
  fullyParallel: true,
  workers: Number(process.env.AQE_WORKERS || 4),
  retries: 0,
  timeout: 30_000,
  expect: { timeout: 4_000 },
  reporter: [['json', { outputFile: `${runDir}/playwright-report.json` }], ['list']],
  use: { ...devices['Desktop Chrome'], baseURL, trace: 'on', screenshot: 'off', video: 'off' },
});
